### ISSUE TITLE
"No handler found for the command" when trying to run ionic commands

### ISSUE THREAD

**Issue by jonathanperis** [jgw96/ionic-vscode#3]
When i try to run Ionic commands after installing the extension on my VS Code, appears the following error: No handler found for the command... Happens in every command i try to start.

Cheers!

![2016-02-29](https://cloud.githubusercontent.com/assets/13967942/13414357/febed87c-df30-11e5-9a95-25ffd395e3d0.png)

**Comment by jgw96** [comment]
@jonathanperis Looks like this might be solved by packaging this extension correctly. By chance did you run npm install before you installed the extension?

**Comment by jonathanperis** [comment]
@jgw96 i've simply downloaded the extension from github, put it on the extension folder like vs code tutorial instruct (https://code.visualstudio.com/Docs/extensions/install-extension) and try to use it later.

I've npm installed and up to date on my machine. -v 3.7.5

**Comment by jgw96** [comment]
Got ya, to get a smooth experience and fix this issue, you should clone this repo and then run npm install before carrying on the rest of those instructions in that article instead of downloading the extension.

**Comment by jgw96** [comment]
Im now updating the readme to reflect this.
